version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/app
      - m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: always
  redis:
    container_name: redisdb
    image: redis:7.0.11-alpine
    ports:
      - "6379:6379"
volumes:
  m2: